### ISSUE TITLE
JsInterop Compatibility

### ISSUE THREAD

**Issue by saruye** [intendia-oss/rxjava-gwt#2]
Hi, 

this is more a question than an actual issue. We are building a shared library between server, web (gwt), mobile(android and ios(j2objc)). I am looking for an elegant pattern for async code in our library. 
On the web, we are using gwt only for our logic layer and exposing all functions with jsinterop. With rxjava-gwt we'll be able to use rxjava in the gwt part of the app, but I am curious if it was possible to also access this from javascript directly. I know there is RxJs for javascript and a try to make this accessible in java (https://gist.github.com/bsorrentino/f678d415432a6f63503bbf8268c00cd8) but this is probably not compatible. 

So this is more a question if you have any experience with this? Is this even possible? Or is it easier to build some wrappers that connect both? 

Thanks for the great library :)
Regards, 
arne

**Comment by ibaca** [comment]
Uoo 😨 , this is not easy. This lib just makes minimal changes to make RxJava compile in GWT. Exposing the API will require important changes, and for example just the `long` used in backpressure is a big problem in JS. Also, exposing the API will limit the awesome feature of pruning all the code not used in your compilation unit. Finally, I think that the API for JS is quite different from the Java API, and using RxJava from JS will not be so pleasant. 

But... I don't think too much about exposing the API in JS, and might be interesting investigating further more. GwtQuery make it work, it can be used in pure java, or it can be exposed in JS, or both. Maybe is not as difficult as I think.

**Comment by saruye** [comment]
Hi ibaca, 

thanks for your quick response! That's what I feared. I was just curious if you already looked into this. We'll start with using RxJava in the java layer for now. If you ever find time to look into this, I would be thankful if you update the ticket :)

**Comment by ibaca** [comment]
Did you find a nice solution?

The more I think about this, the more I think this doesn't make sense because Rx is a multi-language library, exposing some simple interface, something like the [Reactive Streams](https://github.com/reactive-streams/reactive-streams-jvm) which is just a few interfaces with a few methods is much better idea. Even the [Promise/A+](https://promisesaplus.com/) is a good example. Exposing minimal async API is much better than exposing the whole RxJava, even more, Rx has a common language http://reactivex.io/documentation/operators.html but on each language this "common" language is adapted...

> **ReactiveX Is a Polyglot Implementation**
> ReactiveX is currently implemented in a variety of languages, in ways that respect those languages’ idioms, and more languages are being added at a rapid clip.

So again, exposing RxJava is a bad idea. You should note that now, the GWT compiler will purge any code (so operators) that is not used in your code, your GWT output will contain just the code needed. You usually end up using a few operators, so using RxJava do not imply adding the whole RxJava in the JS output. If the JS client want to use Rx, it just need to include the RxJS, and the unique thing you should include is something to wrap your custom and limited Observable type as a RxJS observable, something like YourJsLibUtil.asRxObservable(YourJsLib.someOperator()). You can use the same approach in IOS, but with a YourCustomAsyncType to RxSwift.Observable adapter.

Probably you can add with some hacking or creativity something to YourCustomAsyncType so you can call YourLib.someOperator().asObservable() directly instead of calling some static method. Not sure, but ehehe the idea is that exposing the whole RxJava compiled to other language is not a good idea at all. 😄

**Comment by saruye** [comment]
hi ibaca, 

thanks for the update. I didn't really follow up on the issue. We are not using RxJava together with JsInterop yet. The Problem I have is probably the same for every third party library that I want to expose in javascript. The same for example with Guava Optionals. It would be nice to have some way to access these classes directly in javascript without additional wrapper if they are returned by shared methods. But the wrappers are probably the way to go. 

Thanks again! :)
