### ISSUE TITLE
GWT 2.8.0 compatibility

### ISSUE THREAD

**Issue by chris-becker** [intendia-oss/rxjava-gwt#3]
Hi,

In my current GWT 2.0.8 project, merely adding the dependency for rxjava-gwt:1.0.14-beta1, together with the <inherits name="rx.Rx"/> in my module descriptor, kills the GWT compiler:

[ERROR] Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
[ERROR]         at java.util.Arrays.copyOfRange(Arrays.java:3664)
[ERROR]         at java.lang.String.<init>(String.java:207)
[ERROR]         at java.lang.StringBuilder.toString(StringBuilder.java:407)
[ERROR]         at com.google.gwt.dev.javac.JdtUtil.signature(JdtUtil.java:361)
[ERROR]         at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:99)
[ERROR]         at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor$JsniReferenceCollector.endVisit(GwtAstBuilder.java:314)
[ERROR]         at com.google.gwt.dev.js.ast.JsNameRef.traverse(JsNameRef.java:113)
[ERROR]         at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
[ERROR]         at com.google.gwt.dev.js.ast.JsModVisitor$NodeContext.traverse(JsModVisitor.java:153)
[ERROR]         at com.google.gwt.dev.js.ast.JsModVisitor.doAccept(JsModVisitor.java:176)
[ERROR]         at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
[ERROR]         at com.google.gwt.dev.js.ast.JsInvocation.traverse(JsInvocation.java:88)
[ERROR]         at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)

any Ideas ?

regards

~Chris

**Comment by chris-becker** [comment]
... together with the **&lt;inherits name="rx.Rx"/>** in my module descriptor ...

**Comment by ibaca** [comment]
Uooh! 2.0.8 or 2.8? 😛… hope it's 2.8. Not sure but looks like it's just that you have to increase the jvm `-Xmx`.  This lib should not add too much overhead, do not depends on other libs... it's weird. I suppose that if you add any other library like guava instead of rxjava-gwt you should see the same problem. Or maybe there are an actual bug... but looks improbably.

**Comment by ibaca** [comment]
I'm going to close, doesn't looks like an actual bug. But if you still have doubts do not hesitate to ask.

**Comment by chris-becker** [comment]
'course it was 2.8.0…. sorry.

And increasing –Xmx worked, too… I probably didn’t think of that  because I had it increased already (I’m using Guava & several other libs)… or maybe it was just Friday evening blues ☺

Anyway, thanks for your fast reply… and all the work you did with that lib.
I’m not entirely sure if RxJava in a GWT client is really necessary (but that might be due to my unfamiliarity with the concepts used in there).

I’ll keep trying to solve my actual problems using your implementation, and see where that gets me.

Kind regards

~Chris

Von: Ignacio Baca Moreno-Torres [mailto:notifications@github.com]
Gesendet: Freitag, 18. November 2016 17:26
An: intendia-oss/rxjava-gwt
Cc: Christian Becker; Author
Betreff: Re: [intendia-oss/rxjava-gwt] GWT 2.8.0 compatibility (#3)

Uooh! 2.0.8 or 2.8? &#128539;… hope it's 2.8. Not sure but looks like it's just that you have to increase the jvm -Xmx. This lib should not add too much overhead, do not depends on other libs... it's weird. I suppose that if you add any other library like guava instead of rxjava-gwt you should see the same problem. Or maybe there are an actual bug... but looks improbably.

**Comment by ibaca** [comment]
RxJava might be useful or not, hehe if you need it is useful. Rx make some problems much easier to be solve, and sometime.. is just nicer 😉 like this super compact paint app (https://github.com/ibaca/rxcanvas-gwt/blob/master/src/main/java/rxcanvas/client/RxCanvas.java), but event this is not my actual motivation to make this lib. The main reason is that you can share a lot of code, we have a middle tier for telemetry processing, and we can reuse all the logic in the server or the client using RxJava. I think this is pretty awesome, and is the main motivation to use GWT, to share a lot of logic between client and server. And in our case, this allows to evaluate things seamlessly in the client and the server.

Actually, if you are developing a client only app, probably RxJava is not the best choice (although I think you have not many choices 😜) because the RxJava implementation has a lot of synchronization logic which is unnecessary in JS, and there are lot of places where a custom JS implementation will get much better performance. But... we use it extensively and if you are careful, the performance is pretty acceptable, you usually handle user events, and user events do not occurs by thousands per seconds, so... having actual performance problem is pretty difficult. Same with server responses. So you usually only going to have problems if you flatMap big lists of datas... but again, if you are trying to show this big list of data in the UI your will probably end up having an actual DOM updating performance problem, so again RxJava non-perfect performance will not be a problem.

Share the kind of problem you are trying to solve, I'm interested in how people are using the lib, this maybe motivates me to add GWT support in RxJava 2, which has lot of advantages, because new Observables/Flowable separates the backpressure which contains most of the performance problems in current RxJava GWT.
